<?php

return [
    'energy_equipment' => [
        'name' => 'Energy Equipment',
        'subtypes' => [
            'gas_turbines' => 'Gas Turbines',
            'generator_sets' => 'Generator Sets',
        ],
        'website_url' => 'https://krause-global.com/en/gasturbine.html',
        'statuses' => [
            'inquiry' => 'Inquiry Received',
            'offer_prep' => 'Offer Preparation',
            'offer_sent' => 'Offer Sent',
            'negotiation' => 'Negotiation',
            'contract' => 'Contract Draft',
            'contracted' => 'Contracted',
            'logistics' => 'Logistics',
            'delivered' => 'Delivered',
            'archived' => 'Archived',
        ],
        'document_categories' => [
            'offer' => 'Offer',
            'datasheet' => 'Datasheet',
            'nda' => 'NDA',
            'clarifications' => 'Clarifications',
            'final_offer' => 'Final Offer',
            'contract_draft' => 'Contract Draft',
            'logistics' => 'Logistics',
            'invoice' => 'Invoice',
        ],
    ],

    'energy_commodities' => [
        'name' => 'Energy Commodities',
        'subtypes' => [
            'en590_ulsd_10ppm' => 'EN590 ULSD 10ppm',
        ],
        'website_url' => 'https://krause-global.com/en/energy.html',
        'statuses' => [
            'loi_received' => 'LOI Received',
            'icpo_requested' => 'ICPO Requested',
            'sco_issued' => 'SCO Issued',
            'procedure' => 'Procedure Execution',
            'inspection' => 'Inspection',
            'dip_test' => 'Dip & Pay / Injection',
            'payment' => 'Payment',
            'title_transfer' => 'Title Transfer',
            'completed' => 'Completed',
            'archived' => 'Archived',
        ],
        'document_categories' => [
            'loi_in' => 'LOI Incoming',
            'loi_out' => 'LOI Outgoing',
            'icpo' => 'ICPO',
            'sco' => 'SCO',
            'procedure' => 'Procedure',
            'product_passport' => 'Product Passport',
            'tsr' => 'TSR',
            'sgs' => 'SGS Q&Q',
            'injection_report' => 'Injection Report',
            'atv' => 'ATV',
            'atsc' => 'ATSC',
            'commercial_invoice' => 'Commercial Invoice',
            'certificate_origin' => 'Certificate of Origin',
            'payment_proof' => 'Payment Proof',
            'title_transfer' => 'Title Transfer Proof',
        ],
    ],

    'food' => [
        'name' => 'Food',
        'subtypes' => [
            'grain' => 'Grain',
            'fish' => 'Fish',
            'meat' => 'Meat',
        ],
        'website_url' => 'https://krause-global.com/en/fish.html',
        'statuses' => [
            'loi_received' => 'LOI Received',
            'specification' => 'Specification',
            'contract_draft' => 'Contract Draft',
            'contracted' => 'Contracted',
            'inspection' => 'Inspection',
            'shipping' => 'Shipping',
            'payment' => 'Payment',
            'delivered' => 'Delivered',
            'archived' => 'Archived',
        ],
        'document_categories' => [
            'loi' => 'LOI',
            'specification' => 'Specification',
            'contract_draft' => 'Contract Draft',
            'inspection' => 'Inspection',
            'packing_list' => 'Packing List',
            'bill_of_lading' => 'Bill of Lading',
            'health_certificates' => 'Health Certificates',
            'payment_proof' => 'Payment Proof',
        ],
    ],

    'fertilizer' => [
        'name' => 'Fertilizer',
        'subtypes' => [
            'urea' => 'Urea',
            'npk' => 'NPK',
        ],
        'website_url' => null,
        'statuses' => [
            'inquiry' => 'Inquiry',
            'offer' => 'Offer',
            'negotiation' => 'Negotiation',
            'contracted' => 'Contracted',
            'shipped' => 'Shipped',
            'delivered' => 'Delivered',
            'archived' => 'Archived',
        ],
        'document_categories' => [
            'loi' => 'LOI',
            'offer' => 'Offer',
            'contract' => 'Contract',
            'invoice' => 'Invoice',
            'packing_list' => 'Packing List',
            'certificate_analysis' => 'Certificate of Analysis',
        ],
    ],
];
